#ban_list:
#  # the item or block id
#  'minecraft:tnt':
#    # set true to let player cant pick up this item
#    pickup: true
#    # set true to remove / kill the item entity
#    remove: true
#    # set true to let this item entity cant be create / summon
#    create: true
#  # set true to ban all
#  'minecraft:tnt_minecart': true
ban_list: {}