name: BanItemEntity
version: 1.1.0
author: meowtype.io
main: io.meowtype.ban_item_entity.BanItemEntity
permissions:
  ban-item-entity.*:
    default: op
commands:
  ban-item-entity:
    usage: /ban-item-entity help  or  /banie help
    aliases: [banitementity, "ban_item_entity", banie]
    permission: ban-item-entity.*